# Generated by Django 4.1.3 on 2022-12-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_dibuat"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slur",
            field=models.SlugField(null=True),
        ),
    ]
