# Generated by Django 4.1.3 on 2022-12-10 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_slur"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="slur",
            new_name="slug",
        ),
    ]
